services:
  frontend:
    build:
      context: .  # Utilise le répertoire actuel
      dockerfile: Dockerfile  # Fichier Dockerfile pour builder l'image
    ports:
      - "8201:80"  # Associe le port 80 du conteneur au port 8201 de l’hôte
    environment:
      - NODE_ENV=production  # Mode production
    restart: unless-stopped  # Redémarrage automatique si le conteneur s'arrête
