services:
  frontend:
    build:
      context: .  # Utilise le répertoire actuel pour la construction
      dockerfile: Dockerfile  # Utilise le Dockerfile optimisé
    ports:
      - "8201:80"  # Expose le port 80 du conteneur sur le port 8201 de l'hôte
    environment:
      - NODE_ENV=production  # Indique l'environnement de production
    restart: unless-stopped  # Redémarrage automatique en cas d'arrêt
    container_name: rfess-front  # Nom personnalisé du conteneur
    deploy:
      resources:
        limits:
          cpus: "0.5"  # Limite à 50% d'un CPU pour éviter une surcharge
          memory: 256M  # Limite la mémoire à 256 Mo
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Montre le fichier `nginx.conf` en lecture seule
